nav:
  home: 首页
  archives: 归档
  tags: 标签
  categories: 分类
  about: 关于


posts:
  prev: 上一页
  next: 下一页
  prev_post: 上一篇
  next_post: 下一篇
  read_more: 阅读全文


categories:
  programming: 编程
  entertainment: 娱乐
  games: 游戏
  mathematics: 数学
  japanese: 日本


tags:
  programming: 编程
  python: Python
  php: PHP
  js: JavaScript
  c: C
  c++: C++
  entertainment: 娱乐
  game: 游戏
  math: 数学
  jp: 日语
  ai: AI

counter:
  archives: 篇文章